import {StyleSheet} from 'react-native';
import {fonts} from '../../theme/FontFamily';
import {heightToDp, width, widthToDp} from '../../utils/Dimensions';
import {Colors} from '../../theme';
import {getPlatformSpecificValue, screenToTextSize} from '../../utils/helper';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // paddingHorizontal: 15,
  },
  navbarPageTitle: {
    color: Colors.WHITE,
    fontFamily: fonts.URBANIST_BOLD,
  },
  restaurantFilterBg: {
    height: '100%',
    width: widthToDp(100),
    resizeMode: 'stretch',
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
 
  saveButton: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
  },
  userWiseContainer: {
    justifyContent: 'start',
    flexDirection: 'row',
    height: getPlatformSpecificValue(heightToDp(60), heightToDp(62)),
    // backgroundColor: 'red',
  },
  verticalTabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'relative',
  },
  uselessWrapper: {
    flexDirection: 'row',
    // backgroundColor: '#f00',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    transform: [{rotate: '-90deg'}],
    position: 'absolute',
    left: screenToTextSize(-18),
    top: screenToTextSize(24),
    width: widthToDp(55),
    height: heightToDp(10),
    flex: 1,
    // backgroundColor: '#f00',
  },
  verticalTabBtnGrad: {
    borderRadius: 10,
    flexWrap: 'wrap',
    width: '90%',
    // marginTop: 10,
  },
  verticalTabBtns1: {
    width: widthToDp(20),
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: '#f00',
    // paddingVertical: 10,
  },
  verticalTabBtns2: {
    width: widthToDp(35),
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: '#f00',
  },
  flatlistWrapper: {
    width: widthToDp(80),
    marginLeft: screenToTextSize(15),
    // backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    height: screenToTextSize(60),
    marginTop: screenToTextSize(0),
  },
  menuItemSmallbox: {
    marginHorizontal: 5,
    width: screenToTextSize(40),
    height: screenToTextSize(55),
    alignSelf: 'center',
    backgroundColor: '#7074C422',
    borderColor: '#fff4',
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    gap: 4,
    justifyContent: 'space-between',
    overflow: 'hidden',
    imgCont: {
      // backgroundColor: '#ff0',
      flex: 1,
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      resizeMode: 'cover',
      paddingHorizontaal: screenToTextSize(10),
    },
    image: {
      width: screenToTextSize(35),
      height: screenToTextSize(35),
      objectFit: 'contain',
      backgroundColor: '#88888855',
      borderRadius: 15,
    },
    nameCont: {
      // flex: 1,
      justifyContent: 'space-between',
      width: '100%',
      height: screenToTextSize(12),
      alignItems: 'center',
      flexDirection: 'row',
      paddingHorizontal: screenToTextSize(2),
      // backgroundColor: 'red',
    },
    itemName: {
      color: '#fff',
      fontSize: screenToTextSize(4),
      fontFamily: fonts.URBANIST_BOLD,
    },
    ratingCont: {
      // flex:1,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      // width: '100%',
      // height: screenToTextSize(12),
      // paddingHorizontal: screenToTextSize(2),
    },
    rating: {
      color: '#fff',
      fontSize: screenToTextSize(4),
      fontFamily: fonts.URBANIST_BOLD,
    },
  },  
  categoryWiseTabItem: {
    textAlign: 'center',
    width: '100%',
    fontSize: screenToTextSize(3),
    color: '#fff7',
  },
  categoryWiseTabItemActive: {
    color: '#000',
    textAlign: 'center',
    width: '100%',
    fontSize: screenToTextSize(3),
    paddingVertical: heightToDp(1),
  }, 
  filterHeading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: widthToDp(90),
  },
  shareABillTxt: {
    fontFamily: fonts.URBANIST_EXTRABOLD,
    color: '#00FC92',
    fontSize: 22,
    paddingHorizontaal: 5,
  },
  saveButton: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
  }, 
  restaurantFilterContainer: {
    borderRadius: 25,
    marginTop: 20,
    minHeight: 500,
    paddingHorizontal: 10,
    bottom: 0,
    zIndex: 20,
  },
  filterHeadingText: {
    color: '#fff',
    fontSize: 16,
  },
  cuisineTypeBtns: {
    flexDirection: 'row',
    // justifyContent: 'flex-start',
  },
  cuisineTypeBtnsContainerStyle: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  filterSection: {
    marginBottom: 10,
    flexDirection: 'row',
    // width: '100%',
  },
  priceRange: {
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  priceRangeLabelBottom: {
    marginBottom: 20,
  },
   
  price: {
    color: Colors.GREEN,
    fontSize: 22,
    fontFamily: fonts.URBANIST_BOLD,
  },
  horizontalListStyle: {
    marginTop: 10,
  },
 
 
  verticalPrdListItem: {
    marginHorizontal: 5,
    width: widthToDp(95),
    height: heightToDp(32),
    marginBottom: 15,
    alignSelf: 'center',
    backgroundColor: '#7074C422',
    borderColor: '#fff4',
    borderWidth: 1,
    borderRadius: 26,
    alignItems: 'center',
    gap: 4,
    justifyContent: 'space-between',
    overflow: 'hidden',
    flexDirection: 'row',
    leftCont: {
      width: '50%',
      // backgroundColor: 'brown',
      paddingHorizontal: 15,
    },
    prdNameCont: {
      // backgroundColor: 'red',
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 5,
    },
    prdName: {
      color: 'white',
      fontSize: screenToTextSize(5),
      fontFamily: fonts.URBANIST_BOLD,
    },
    prdRatingCont: {
      marginLeft: 15,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    prdRating: {
      color: 'white',
    },
    prdRatingStar: {},
    prdAllergiesCont: {
      flexDirection: 'row',
      // backgroundColor: '#ff00ff',
    },
    prdAllergiesBg: {
      width: 20,
      height: 20,
      marginRight: 5,
      // backgroundColor: '#ff00ff',
      // flex: 1,
      // justifyContent: 'center',
      // alignItems: 'center'
    },
    prdAllergies: {
      width: 16,
      height: 16,
      margin: 5,
      padding: 10,
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    prdPricingCont: {
      flexDirection: 'row',
    },
    rightCont: {
      width: '50%',
      // backgroundColor: 'green',
      flexDirection: 'row',
      justifyContent: 'flex-end',
      paddingHorizontal: 15,
    },
    imgCont: {
      backgroundColor: '#88888855',
      borderRadius: 20,
      padding: 5,
      justifyContent: 'center',
      alignItems: 'center',
      resizeMode: 'cover',
      paddingHorizontaal: screenToTextSize(10),
    },
    image: {
      width: screenToTextSize(25),
      height: screenToTextSize(25),
      objectFit: 'contain',
      // backgroundColor: '#88888855',
      borderRadius: 15,
    },
  },
});
export {styles};
